spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  social:
    facebook:
      app-id: 233668646673605
      app-secret: 233668646673605=33b17e044ee6a4fa383f46ec6e28ea1d
    google:
      app-id: 321145677628-o8448kficmgrvn7elcknaaapbu2035ac.apps.googleusercontent.com
      app-secret: wTc_d16c20TN0UjvJlGXw3Eu

github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
logging:
  level:
    spring:
      security: debug
