import type { NextPage } from 'next';
import Head from 'next/head';
import Contacts from '../../components/Contacts';
import Educations from '../../components/Educations';
import Header from '../../components/Header';
import BestSkillsPies from '../../components/skills/BestSkillsPies';
import Portfolio from '../../components/Portfolio';
import Timeline from '../../components/Timeline';
import SkillsChipses from '../../components/skills/SkillsChipses';
import { useTranslation } from '../../src/translator';
import { useRouter } from 'next/router';

import styles from '../../styles/Home.module.css';

export async function getStaticProps() {
  return {
    props: {
      // ...(await serverSideTranslations(locale, ['default'])),
      // Will be passed to the page component as props
    },
  };
}

const ResumePage: NextPage = () => {
  const router = useRouter();
  const { language } = router.query;

  const { t } = useTranslation();

  console.log(language);

  return (
    <div className={styles.container}>
      <Head>
        <title>Resume - The Mad Scientist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
      </Head>

      <Header />

      <div className="wrapper container">
        <section
          className="experiences-section section"
          id="experiences-section"
        >
          <h2 className="section-title">
            {t('experiences')}
          </h2>
          <div className="timeline">
            <Timeline />
          </div>
        </section>

        <section className="education-section section" id="eudcation-section">
          <Educations />
        </section>

        <section
          className="skills-section section text-center"
          id="skills-section"
        >
          <h2 className="section-title">
            {t('knowledgebase')}
          </h2>

          <BestSkillsPies/>

          <SkillsChipses/>
        </section>

        <section className="portfolio-section section" id="portfolio-section">
          <h2 className="section-title">Portfolio</h2>
          <ul className="filters clearfix" id="filters">
            <li className="type active" data-filter="*">
              All
            </li>
            <li className="type" data-filter=".backend">
              Back-end
            </li>
            <li className="type" data-filter=".frontend">
              Front-end
            </li>
            <li className="type" data-filter=".appz">
              Application
            </li>
          </ul>
          <div className="items-wrapper isotope row">
            <Portfolio />
          </div>
        </section>

        <Contacts />
      </div>
    </div>
  );
};

export default ResumePage;
