import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'react-i18next';
import Contacts from '../components/Contacts';
import Educations from '../components/Educations';
import Header from '../components/Header';
import Knowledgebase from '../components/Knowledgebase';
import Portfolio from '../components/Portfolio';
import Timeline from '../components/Timeline';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { t } = useTranslation('default');

  return (
    <div className={styles.container}>
      <Head>
        <title>Resume - The Mad Scientist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
      </Head>

      <Header />

      <div className="wrapper container">
        <section
          className="experiences-section section"
          id="experiences-section"
        >
          <h2 className="section-title">
            {t('experiences')}
          </h2>
          <div className="timeline">
            <Timeline />
          </div>
        </section>

        <section className="education-section section" id="eudcation-section">
          <Educations />
        </section>

        <section
          className="skills-section section text-center"
          id="skills-section"
        >
          <h2 className="section-title">
            {t('knowledgebase')}
          </h2>
          <div className="top-skills">
            <h3 className="subtitle">
              {t('skills-subtitle')}
            </h3>
            <div className="row">
              <Knowledgebase />
            </div>
          </div>
          <div className="other-skills">
            <h3 className="subtitle">
              {t('another-experiences')}
            </h3>
            <div className="misc-skills">
              <span className="skill-tag">HTML5</span>
              <span className="skill-tag">CSS3</span>
              <span className="skill-tag">SASS/SCSS</span>
              <span className="skill-tag">Git/GitFlow</span>
              <br />
              <span className="skill-tag text-danger">
                J2EE (JBossAS/Wildfly/WebSphere)
              </span>
              <span className="skill-tag text-danger">Spring/SpringBoot</span>
              <span className="skill-tag text-danger">C#</span>
              <span className="skill-tag text-danger">
                Qt5 (Cross Platform Development)
              </span>
              <br />
              <span className="skill-tag text-success">PostgreSQL</span>
              <span className="skill-tag text-success">MySQL</span>
              <span className="skill-tag text-success">Oracle 9+</span>
              <span className="skill-tag text-success">MongoDB</span>
            </div>
          </div>
        </section>

        <section className="portfolio-section section" id="portfolio-section">
          <h2 className="section-title">Portfolio</h2>
          <ul className="filters clearfix" id="filters">
            <li className="type active" data-filter="*">
              All
            </li>
            <li className="type" data-filter=".backend">
              Back-end
            </li>
            <li className="type" data-filter=".frontend">
              Front-end
            </li>
            <li className="type" data-filter=".appz">
              Application
            </li>
          </ul>
          <div className="items-wrapper isotope row">
            <Portfolio />
          </div>
        </section>

        <Contacts />
      </div>
    </div>
  );
};

export default Home;
